name: Publish release

on:
  push:
    branches:
      - master

jobs:
  validate_gradle:
    name: Validate gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
  detekt:
    needs: [ validate_gradle ]
    name: "Check project by detekt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt
  tests:
    needs: [ detekt ]
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
  publish:
    needs: [ detekt, tests ]
    name: Publish library at mavenCentral
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Prebuild library
        run: ./gradlew publishToMavenLocal --stacktrace
      - name: Publish library
        run: ./gradlew publish --no-parallel --stacktrace
  release:
    needs: [ publish, detekt ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: SebRollen/toml-action@v1.0.2
        id: version
        with:
          file: 'gradle/libs.versions.toml'
          field: 'versions.plugin-version'
      - uses: SebRollen/toml-action@v1.0.2
        id: name
        with:
          file: 'gradle/libs.versions.toml'
          field: 'versions.plugin-name'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.value }}
          name: ${{ steps.name.outputs.value }} - ${{ steps.version.outputs.value }}
          draft: false
          prerelease: false